# Generated by Django 2.2.2 on 2019-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name'], 'verbose_name': 'enlace', 'verbose_name_plural': 'enlaces'},
        ),
        migrations.AddField(
            model_name='link',
            name='font_awesome',
            field=models.CharField(default='fa-', max_length=75, verbose_name='Font-awesome'),
        ),
    ]
