# Generated by Django 2.2.2 on 2019-07-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190707_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='font_awesome',
        ),
    ]
